version: "3.9"
services:
   db:
     image: mysql
     restart: always
     ports:
      - '3306:3306'
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: flask_demo
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin
     volumes:
       - ./db_data:/var/lib/mysql
     networks:
       - wpsite
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - '8080:80'
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: root
     networks:
       - wpsite
networks:
  wpsite:
